### ISSUE TITLE
"main" points to source file

### ISSUE THREAD

**Issue by gausie** [kennetpostigo/react-google-login-component#1] opened 2016-06-21 11:56 UTC
"main" should point to the build file, otherwise I need to configure my build to load a node_module dependency through Babel (which is a bad idea)

I would submit a PR but not sure if I should point the "main" value in package.json to the minified build file or not.

**Comment by kennetpostigo** [comment] 2016-06-21 16:18
Thank you for pointing this out @gausie will fix now :)

**Comment by kennetpostigo** [comment] 2016-06-21 16:29
@gausie just fixed the entry point. Let me know if there are any more problems. Feel free to close the issue if the problem is resolved.

**Closed as completed** 2016-07-15 12:12 UTC
